FORMAT: 1A

# Example code for using The Grid API

[Example code directory on Github](https://github.com/the-grid/apidocs/tree/master/code-examples)

# Dart


## Authenticate and get user information


    <!-- include(code-examples/dart/auth-getuser.dart) -->


<!-- include(code-examples/dart/README.md) -->


# Python

## Share a file

    <!-- include(code-examples/python/share-file.py) -->


<!-- include(code-examples/python/README.md) -->
