FORMAT: 1A

[Example code directory on Github](https://github.com/the-grid/apidocs/tree/master/code-examples)

# Dart


## Authenticate and get user information


    <!-- include(code-examples/dart/auth-getuser.dart) -->


<!-- include(code-examples/dart/README.md) -->
