FORMAT: 1A

# The Grid API

Want to get straight to the details?

## API Endpoints

* [Authentication](authentication.html)
* [Content Management API](api.html)
* [User Management API](passport.html)
* [Notifications API](notifications.html)
* [Design Systems](designsystem.html)
* [Code examples](examplecode.html)

# Purpose

[The Grid](https://thegrid.io/) is a next-generation web publishing platform.
The service provides a full user experience for making, editing content
across multiple devices, but also has a complete API available.
This document describes that API and how it can be used by developers, including third-party.

<iframe width="560" height="315" src="https://www.youtube.com/embed/6WC51nDYgCw" frameborder="0" allowfullscreen></iframe>

Functionality provided includes

* Webpage auto-design and layout
* Content import and analysis
* Image processing
* Website serving
* Handling payments (TBD)

What The Grid is not:

Not a web-hosting platform to run arbitrary PHP/Python/Ruby or databases on.

# Programming language support

The Grid API is based on HTTP REST with JSON payloads and OAuth2 authentication.
It can be used from any programming language with libraries supporting these technologies.
Popular choices include Python, Ruby, JavaScript, Java, C#.

Unless otherwise noted, all API endpoints are [CORS](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing) enabled.
That means you can use the API in the browser on any website, also those who are not made with The Grid.

# Access

API access is available to all users on The Grid.
If you wish to develop with The Grid, [get your plan](https://plans.thegrid.io/pro).

When your plan has been activated, you may log in and register new apps
on your [accounts page](https://passport.thegrid.io/)

# API quotas

API usage is tracked against the app ID and user UUID which is used to authenticate the request.

We reserve the right to impose quotas (soft or hard), especially on heavy processing operations
like image analytics and page solving.
If you think your app or user may hit quotas limits, get in touch.

# Known consumers

Existing examples of apps and libraries using this API.

* The Grid Android app
* The Grid iOS app
* The Grid Chrome extension
* [thegrid.io](https://thegrid.io) website, including purchasing process

Libraries

* [passport-thegrid](https://www.npmjs.com/package/passport-thegrid):
Authentication strategy for [Passport.js](http://passportjs.org/)

# Issues or Questions?

This API documentation is [on GitHub](https://github.com/the-grid/apidocs).
Got any questions or found issues in the documentation?
[File issues](https://github.com/the-grid/apidocs/issues)
or create a [pull request](https://github.com/the-grid/apidocs/pulls).
